//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_GCCCine.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GCC_Sillas
    {
        public int SillasId { get; set; }
        public Nullable<int> SalaId { get; set; }
        public string NumeroSilla { get; set; }
    
        public virtual GCC_Salas GCC_Salas { get; set; }
    }
}
