//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_GCCCine.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using WCF_GCCCine.Clases;

    public partial class GCCCineEntities : DbContext
    {
        public GCCCineEntities()
            : base("name=GCCCineEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Funciones> Funciones { get; set; }
        public virtual DbSet<GCC_Peliculas> GCC_Peliculas { get; set; }
        public virtual DbSet<GCC_Salas> GCC_Salas { get; set; }
        public virtual DbSet<GCC_Sillas> GCC_Sillas { get; set; }
    }
}
